# Generated by Django 4.2.10 on 2024-02-26 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('abbrev', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='save_mp3_translations.language')),
            ],
        ),
        migrations.CreateModel(
            name='WordsPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_word', to='save_mp3_translations.word')),
                ('translated_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translated_word', to='save_mp3_translations.word')),
            ],
        ),
    ]
