# Generated by Django 4.2.5 on 2023-09-21 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uczniowie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numer_klasy', models.CharField(max_length=10)),
                ('rok', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParaUczniow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ile_razy_byla_utworzona', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('uczen_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uczen_1', to='uczniowie.uczen')),
                ('uczen_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uczen_2', to='uczniowie.uczen')),
            ],
        ),
        migrations.DeleteModel(
            name='KombinacjaParUczniow',
        ),
        migrations.AddField(
            model_name='uczen',
            name='klasa',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='uczniowie.klasa'),
            preserve_default=False,
        ),
    ]
