# Generated by Django 4.2.5 on 2023-09-24 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uczniowie', '0002_klasa_parauczniow_delete_kombinacjaparuczniow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KombinacjaPar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kombinacja', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='klasa',
            name='numer_klasy',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='uczen',
            name='imie',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
