# Generated by Django 4.2.5 on 2023-09-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uczniowie', '0003_kombinacjapar_alter_klasa_numer_klasy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parauczniow',
            name='para_w_tym_tygodniu',
            field=models.BooleanField(default=False),
        ),
    ]
